spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/moviedb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nwaizugbechukwuemeka38@gmail.com
    password: vqgk udmd zpyj bnjz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/
cloudinary:
  cloud-name: dn0bqllkd
  api-key: 719168781167538
  api-secret: c44hMt4h7TgO-gP5vRTAxf7SIuU

#base:
#  url: "http://localhost:9000"
